name: Linters

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  eslint:
    name: ESLint
    runs-on: debian-10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Setup ESLint
        run: |
          npm install --save-dev eslint eslint-config-airbnb eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-react eslint-plugin-react-hooks
          [ -f .eslintrc.json ]
      - name: ESLint Report
        run: npx eslint .
  stylelint:
    name: Stylelint
    runs-on: debian-10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Setup Stylelint
        run: |
          npm install --save-dev stylelint stylelint-scss stylelint-config-standard stylelint-csstree-validator
          [ -f .stylelintrc.json ]
      - name: Stylelint Report
        run: npx stylelint "**/*.{css,scss}"